#!/bin/sh
qlmanage -ts20 -o.  AppIcon.svg; mv AppIcon.svg.png "AppIcon-20.png"
qlmanage -ts40 -o.  AppIcon.svg; mv AppIcon.svg.png "AppIcon-20@2x.png"
qlmanage -ts60 -o.  AppIcon.svg; mv AppIcon.svg.png "AppIcon-20@3x.png"
qlmanage -ts29 -o.  AppIcon.svg; mv AppIcon.svg.png "AppIcon-29.png"
qlmanage -ts58 -o.  AppIcon.svg; mv AppIcon.svg.png "AppIcon-29@2x.png"
qlmanage -ts87 -o.  AppIcon.svg; mv AppIcon.svg.png "AppIcon-29@3x.png"
qlmanage -ts40 -o.  AppIcon.svg; mv AppIcon.svg.png "AppIcon-40.png"
qlmanage -ts80 -o.  AppIcon.svg; mv AppIcon.svg.png "AppIcon-40@2x.png"
qlmanage -ts120 -o. AppIcon.svg; mv AppIcon.svg.png "AppIcon-40@3x.png"
qlmanage -ts120 -o. AppIcon.svg; mv AppIcon.svg.png "AppIcon-60@2x.png"
qlmanage -ts180 -o. AppIcon.svg; mv AppIcon.svg.png "AppIcon-60@3x.png"
qlmanage -ts76 -o.  AppIcon.svg; mv AppIcon.svg.png "AppIcon-76.png"
qlmanage -ts152 -o. AppIcon.svg; mv AppIcon.svg.png "AppIcon-76@2x.png"
qlmanage -ts167 -o. AppIcon.svg; mv AppIcon.svg.png "AppIcon-83.5@2x.png"
